### ISSUE TITLE
Make sure "sum" can't be zero

### ISSUE THREAD

**Issue by Vicsuka** [BME-MIT-IET/Brogrammers-iet-2019#11]
![image](https://user-images.githubusercontent.com/13932484/57200401-d8cd9600-6f8b-11e9-8752-d016cb44c44f.png)

**Comment by Vicsuka** [comment]
https://github.com/BME-MIT-IET/Brogrammers-iet-2019/pull/13/commits/8cff2c263c842f8d179a9fbb75b1d6878baf2dcf

**Comment by csmark97** [comment]
Great!
