### ISSUE TITLE
Continuous integration

### ISSUE THREAD

**Issue by Vicsuka** [BME-MIT-IET/Brogrammers-iet-2019#2]
Sync GitHub project with Travis CI.

**Comment by csmark97** [comment]
![image](https://user-images.githubusercontent.com/36475822/57199531-5390b400-6f80-11e9-9129-ec505b30ea21.png)

Travis is successfully configured.

**Comment by csmark97** [comment]
![image](https://user-images.githubusercontent.com/36475822/57199583-0d882000-6f81-11e9-8ff3-5fa844fff2d6.png)

Travis is successfully configured
