### ISSUE TITLE
Running static analysis tool and reviewing indicated errors

### ISSUE THREAD

**Issue by csmark97** [BME-MIT-IET/Brogrammers-iet-2019#3]
**Description**
Use one of these: _SonarQube, FindBugs, VS Code Analyzer, Codacy, Coverity Scan..._

**Comment by Vicsuka** [comment]
Project configured to be analized, running SonarQube on project successfully. 

![image](https://user-images.githubusercontent.com/13932484/57199673-f695fd80-6f81-11e9-8ae4-027566c73965.png)

![image](https://user-images.githubusercontent.com/13932484/57199708-512f5980-6f82-11e9-9848-792370ff22ac.png)
