### ISSUE TITLE
Change condition

### ISSUE THREAD

**Issue by Vicsuka** [BME-MIT-IET/Brogrammers-iet-2019#4]
![image](https://user-images.githubusercontent.com/13932484/57199745-cf8bfb80-6f82-11e9-94d0-074b43fd3a64.png)

**Comment by csmark97** [comment]
https://github.com/BME-MIT-IET/Brogrammers-iet-2019/commit/a39b557ba935da7029a4a3e1cd7839debde7ebe2

Condition removed.
