### ISSUE TITLE
NullPointerException could be thrown

### ISSUE THREAD

**Issue by csmark97** [BME-MIT-IET/Brogrammers-iet-2019#41]
![image](https://user-images.githubusercontent.com/36475822/58281620-cd5bd680-7da3-11e9-974a-e5609b6fdb80.png)

**Comment by csmark97** [comment]
![image](https://user-images.githubusercontent.com/36475822/58281995-cbdede00-7da4-11e9-8f0e-2d2421f7cb6d.png)

**Comment by csmark97** [comment]
![image](https://user-images.githubusercontent.com/36475822/58282034-ddc08100-7da4-11e9-8c94-4834fffeedd3.png)

**Comment by zolirevesz** [comment]
Ehhez amúgy mit javasol a sonarqube, min kéne változtatni?
