### ISSUE TITLE
Parameter 1 to this call is marked

### ISSUE THREAD

**Issue by csmark97** [BME-MIT-IET/Brogrammers-iet-2019#44]
![image](https://user-images.githubusercontent.com/36475822/58282067-f761c880-7da4-11e9-9a41-97f248b7ed60.png)

**Comment by csmark97** [comment]
00bfd0a0d19e3e58a9eaf08554f4ac13699a06d1 commit fixed this

**Comment by Vicsuka** [comment]
Issue fixed!
