### ISSUE TITLE
Cast operands to long

### ISSUE THREAD

**Issue by Vicsuka** [BME-MIT-IET/Brogrammers-iet-2019#5]
![image](https://user-images.githubusercontent.com/13932484/57199772-1679f100-6f83-11e9-876d-366d085cd066.png)

**Comment by csmark97** [comment]
https://github.com/BME-MIT-IET/Brogrammers-iet-2019/commit/82fc32ee36fbf8327375a4baa4c33628c7f9ae4d

**Comment by Vicsuka** [comment]
Well done!

**Comment by Vicsuka** [comment]
@csmark97 How is the development going?

**Comment by csmark97** [comment]
@Vicsuka thanks for the interest, it's a great fun! Already done.
