### ISSUE TITLE
"YYYY" instead of "yyyy"

### ISSUE THREAD

**Issue by csmark97** [BME-MIT-IET/Brogrammers-iet-2019#7]
![image](https://user-images.githubusercontent.com/36475822/57199871-918fd700-6f84-11e9-9ebc-7932ddc9defa.png)

**Comment by Vicsuka** [comment]
[https://github.com/BME-MIT-IET/Brogrammers-iet-2019/commit/821dd508178538aa53252c46a5a7219034c03508](url)

**Comment by Vicsuka** [comment]
https://github.com/BME-MIT-IET/Brogrammers-iet-2019/commit/821dd508178538aa53252c46a5a7219034c03508

**Comment by zolirevesz** [comment]
Bug fixed in the commit mentioned above.
